version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80

  web:
    volumes:
      - ..:/usr/app/
      - /usr/app/node_modules
    build:
      context: ..
      args:
        APP_PORT: $APP_PORT
    ports:
      - $APP_PORT:$APP_PORT

